language: node_js
node_js: '7'
dist: trusty
sudo: false
git:
  depth: 1
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - CLOUDSDK_PYTHON_SITEPACKAGES=1
cache:
  directories:
  - node_modules
install:
  - npm install -g bower gulp
  - npm install
  - npm --prefix ./travis install ./travis
script:
  # - npm run build
  - npm run lint
  # - npm run test
after_success:
  - export LH_MIN_PASS_SCORE=85
  - export GAE_APP_ID=cr-status
  - ./travis/deploy_pr_gae.sh

notifications:
  webhooks:
    urls:
      - https://88a825eb.ngrok.io/github_status
    on_success: always # default: always
    on_failure: never # default: always
    on_start: change   # default: never
    on_cancel: never # default: always
    #on_error: always # default: always

# Ideally we could use provider: gae, builds triggered from pull requests never
# trigger a deploy.
# https://docs.travis-ci.com/user/deployment/google-app-engine/
# deploy:
#  provider: gae
#  config: app.yaml
#  keyfile: gcloud-client-secret.json
#  project: $GAE_APP_ID
#  #on:
#  #  all_branches: true
#  #  condition: $MY_ENV = super_awesome
#  version: staging
#  no_promote: true
#  skip_cleanup: true
# # after_deploy:
# #   # TODO