language: node_js
node_js: '7'
dist: trusty
sudo: false
git:
  depth: 1
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - CLOUDSDK_PYTHON_SITEPACKAGES=1
  - GAE_APP_ID=cr-status
cache:
  directories:
  - node_modules
install:
  - npm install -g bower gulp
  - npm install
  - npm --prefix ./travis install ./travis
script:
  # - npm run build
  - npm run lint
  # - npm run test
after_success:
  - export LH_MIN_PASS_SCORE=93
  - export LH_TEST_URL=https://lighthouse-ci-staging-dot-cr-status.appspot.com
  - ./travis/deploy_pr_gae.sh
  - node travis/runLighthouse.js
