language: node_js
node_js: '7'
dist: trusty
sudo: false
git:
  depth: 1
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - CLOUDSDK_PYTHON_SITEPACKAGES=1
cache:
  directories:
  - node_modules
install:
  - npm install -g bower
  - npm install -g gulp
  - npm install
  - npm --prefix ./travis install ./travis
#before_script:
#  - export GAE_APP_ID=cr-status
#  - export LH_MIN_PASS_SCORE=85
script:
  # - npm run build
  - npm run lint
  # - npm run test
after_success:
  - export GAE_APP_ID=cr-status
  - export LH_MIN_PASS_SCORE=85
  # - source ./travis/install_google_cloud_sdk.sh
  - source ./travis/deploy_pr.sh
  - node ./travis/updateGithubStatus.js pending $STAGED_URL
  - node ./travis/runLighthouse.js $STAGED_URL
  - node ./travis/updateGithubStatus.js $LH_STATUS $STAGED_URL $LH_SCORE
  #- node ./travis/removeStagedPRs.js
#after_failure:
#  - node ./travis/updateGithubStatus.js failure $STAGED_URL

# Ideally we could use provider: gae, but we need to stage the PR to an URL,
# not deploy the site after a succesful build.
#deploy:
#  provider: gae
#  config: "./app.yaml"
#  keyfile: gcloud-client-secret.json
#  project: lighthouse-ci
#  #on: staging-branch
#  version: staging
#  no_promote: true
